# Generated by Django 6.0.1 on 2026-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the record', max_length=255)),
                ('from_field', models.CharField(help_text='Source location', max_length=100, verbose_name='From')),
                ('to_field', models.CharField(help_text='Destination location', max_length=100, verbose_name='To')),
                ('volume_in_l', models.DecimalField(decimal_places=2, help_text='Volume in litres', max_digits=10, verbose_name='Volume in L')),
                ('start_date', models.DateField(help_text='Start date')),
                ('sg_start', models.FloatField(help_text='Starting specific gravity', verbose_name='SG Start')),
                ('date', models.DateField(help_text='End date')),
                ('sg_end', models.FloatField(help_text='Ending specific gravity', verbose_name='SG End')),
                ('abv', models.FloatField(help_text='Alcohol by volume (percent)', verbose_name='ABV')),
                ('lal', models.FloatField(help_text='Litres of Absolute Alcohol', verbose_name='LAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ['-date'],
            },
        ),
    ]
