# Generated by Django 6.0.1 on 2026-01-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abv',
            field=models.FloatField(blank=True, help_text='Alcohol by volume (percent)', null=True, verbose_name='ABV'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(blank=True, help_text='End date', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='from_field',
            field=models.CharField(blank=True, help_text='Source location', max_length=100, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lal',
            field=models.FloatField(blank=True, help_text='Litres of Absolute Alcohol', null=True, verbose_name='LAL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sg_end',
            field=models.FloatField(blank=True, help_text='Ending specific gravity', null=True, verbose_name='SG End'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sg_start',
            field=models.FloatField(blank=True, help_text='Starting specific gravity', null=True, verbose_name='SG Start'),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='to_field',
            field=models.CharField(blank=True, help_text='Destination location', max_length=100, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='record',
            name='volume_in_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume in litres', max_digits=10, null=True, verbose_name='Volume in L'),
        ),
    ]
