# Generated by Django 5.1.7 on 2026-01-20 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='records_data',
        ),
        migrations.AddField(
            model_name='batch',
            name='fermentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='distillery.fermentationrecord'),
        ),
        migrations.AddField(
            model_name='batch',
            name='spirit_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_spirit1', to='distillery.distillationrecord'),
        ),
        migrations.AddField(
            model_name='batch',
            name='spirit_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_spirit2', to='distillery.distillationrecord'),
        ),
        migrations.AddField(
            model_name='batch',
            name='totals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='distillery.totalsrecord'),
        ),
        migrations.AddField(
            model_name='batch',
            name='wash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_wash', to='distillery.distillationrecord'),
        ),
    ]
