# Generated by Django 6.0.1 on 2026-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0002_alter_record_abv_alter_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_number', models.IntegerField(help_text='Batch number', unique=True, verbose_name='Batch Number')),
                ('recipe', models.CharField(help_text='Recipe name', max_length=255, verbose_name='Recipe')),
                ('records_data', models.JSONField(default=dict, help_text='Dictionary of records for each stage', verbose_name='Records Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['batch_number'],
            },
        ),
    ]
