# Generated by Django 5.1.7 on 2026-01-20 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0002_remove_batch_records_data_batch_fermentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Wash Run', help_text='Description of the run', max_length=255)),
                ('faints_in_l', models.DecimalField(blank=True, decimal_places=2, help_text='Faints input in litres', max_digits=10, null=True, verbose_name='Faints in (L)')),
                ('from_field', models.CharField(blank=True, help_text='Source location', max_length=100, null=True, verbose_name='From')),
                ('to_field', models.CharField(blank=True, help_text='Destination location', max_length=100, null=True, verbose_name='To')),
                ('volume_in_l', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in litres', max_digits=10, null=True, verbose_name='Volume (L)')),
                ('start_date', models.DateField(blank=True, help_text='Start date', null=True)),
                ('date', models.DateField(blank=True, help_text='End date', null=True, verbose_name='End Date')),
                ('fores_out', models.DecimalField(blank=True, decimal_places=2, help_text='Foreshots output', max_digits=10, null=True, verbose_name='Fores out (L)')),
                ('heads_out', models.DecimalField(blank=True, decimal_places=2, help_text='Heads output', max_digits=10, null=True, verbose_name='Heads out (L)')),
                ('harts_out', models.DecimalField(blank=True, decimal_places=2, help_text='Hearts output', max_digits=10, null=True, verbose_name='Harts out (L)')),
                ('harts_out_location', models.CharField(blank=True, help_text='Location of hearts output', max_length=100, null=True, verbose_name='Hearts Out Location')),
                ('tails_out', models.DecimalField(blank=True, decimal_places=2, help_text='Tails output', max_digits=10, null=True, verbose_name='Tails out (L)')),
                ('waste_out', models.DecimalField(blank=True, decimal_places=2, help_text='Waste output', max_digits=10, null=True, verbose_name='Waste out (L)')),
                ('abv_harts', models.FloatField(blank=True, help_text='ABV of hearts cut', null=True, verbose_name='ABV (Harts) %')),
                ('lal', models.FloatField(blank=True, help_text='Litres of Absolute Alcohol', null=True, verbose_name='LAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wash Record',
                'verbose_name_plural': 'Wash Records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='distillationrecord',
            name='faints_out_location',
            field=models.CharField(blank=True, help_text='Location of faints output', max_length=100, null=True, verbose_name='Faints Out Location'),
        ),
        migrations.AddField(
            model_name='distillationrecord',
            name='harts_out_location',
            field=models.CharField(blank=True, help_text='Location of hearts output', max_length=100, null=True, verbose_name='Hearts Out Location'),
        ),
        migrations.AddField(
            model_name='totalsrecord',
            name='harts_abv',
            field=models.FloatField(blank=True, help_text='ABV of stored hearts', null=True, verbose_name='Hearts ABV (%)'),
        ),
        migrations.AddField(
            model_name='totalsrecord',
            name='harts_to_storage_location',
            field=models.CharField(blank=True, help_text='Location of hearts storage', max_length=100, null=True, verbose_name='Hearts to Storage Location'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='wash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='distillery.washrecord'),
        ),
    ]
