# Generated by Django 5.1.7 on 2026-01-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0003_washrecord_distillationrecord_faints_out_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrecord',
            name='sg_end',
            field=models.FloatField(blank=True, help_text='Ending specific gravity (Final Gravity)', null=True, verbose_name='SG End'),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='sg_start',
            field=models.FloatField(blank=True, help_text='Starting specific gravity', null=True, verbose_name='SG Start'),
        ),
        migrations.AlterField(
            model_name='washrecord',
            name='abv_harts',
            field=models.FloatField(blank=True, help_text='ABV of hearts cut (auto-calculated from SG)', null=True, verbose_name='ABV (Harts) %'),
        ),
        migrations.AlterField(
            model_name='washrecord',
            name='lal',
            field=models.FloatField(blank=True, help_text='Litres of Absolute Alcohol (auto-calculated)', null=True, verbose_name='LAL'),
        ),
    ]
