# Generated by Django 5.1.7 on 2026-01-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0003_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
