# Generated by Django 5.1.7 on 2026-01-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0004_washrecord_sg_end_washrecord_sg_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distillationrecord',
            old_name='harts_out_location',
            new_name='hearts_out_location',
        ),
        migrations.RenameField(
            model_name='totalsrecord',
            old_name='harts_abv',
            new_name='hearts_abv',
        ),
        migrations.RenameField(
            model_name='totalsrecord',
            old_name='harts_to_storage_location',
            new_name='hearts_to_storage_location',
        ),
        migrations.RenameField(
            model_name='washrecord',
            old_name='harts_out_location',
            new_name='hearts_out_location',
        ),
        migrations.RemoveField(
            model_name='distillationrecord',
            name='abv_harts',
        ),
        migrations.RemoveField(
            model_name='distillationrecord',
            name='harts_out',
        ),
        migrations.RemoveField(
            model_name='washrecord',
            name='abv_harts',
        ),
        migrations.RemoveField(
            model_name='washrecord',
            name='harts_out',
        ),
        migrations.AddField(
            model_name='distillationrecord',
            name='abv_hearts',
            field=models.FloatField(blank=True, help_text='ABV of hearts cut', null=True, verbose_name='ABV (Hearts) %'),
        ),
        migrations.AddField(
            model_name='distillationrecord',
            name='hearts_out',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hearts output', max_digits=10, null=True, verbose_name='Hearts out (L)'),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='abv_hearts',
            field=models.FloatField(blank=True, help_text='ABV of hearts cut (auto-calculated from SG)', null=True, verbose_name='ABV (Hearts) %'),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='hearts_out',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hearts output', max_digits=10, null=True, verbose_name='Hearts out (L)'),
        ),
    ]
