# Generated by Django 5.1.7 on 2026-01-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0004_alter_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistillationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of the run', max_length=255)),
                ('faints_in_l', models.DecimalField(blank=True, decimal_places=2, help_text='Faints input in litres', max_digits=10, null=True, verbose_name='Faints in (L)')),
                ('from_field', models.CharField(blank=True, help_text='Source location', max_length=100, null=True, verbose_name='From')),
                ('to_field', models.CharField(blank=True, help_text='Destination location', max_length=100, null=True, verbose_name='To')),
                ('volume_in_l', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in litres', max_digits=10, null=True, verbose_name='Volume (L)')),
                ('start_date', models.DateField(blank=True, help_text='Start date', null=True)),
                ('date', models.DateField(blank=True, help_text='End date', null=True, verbose_name='End Date')),
                ('abv_harts', models.FloatField(blank=True, help_text='ABV of hearts cut', null=True, verbose_name='ABV (Harts) %')),
                ('lal', models.FloatField(blank=True, help_text='Litres of Absolute Alcohol', null=True, verbose_name='LAL')),
                ('fores_out', models.DecimalField(blank=True, decimal_places=2, help_text='Foreshots output', max_digits=10, null=True, verbose_name='Fores out (L)')),
                ('heads_out', models.DecimalField(blank=True, decimal_places=2, help_text='Heads output', max_digits=10, null=True, verbose_name='Heads out (L)')),
                ('harts_out', models.DecimalField(blank=True, decimal_places=2, help_text='Hearts output', max_digits=10, null=True, verbose_name='Harts out (L)')),
                ('tails_out', models.DecimalField(blank=True, decimal_places=2, help_text='Tails output', max_digits=10, null=True, verbose_name='Tails out (L)')),
                ('waste_out', models.DecimalField(blank=True, decimal_places=2, help_text='Waste output', max_digits=10, null=True, verbose_name='Waste out (L)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distillation Record',
                'verbose_name_plural': 'Distillation Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FermentationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Fermentation', help_text='Description', max_length=255)),
                ('to_field', models.CharField(blank=True, help_text='Destination location', max_length=100, null=True, verbose_name='To')),
                ('volume_in_l', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in litres', max_digits=10, null=True, verbose_name='Volume (L)')),
                ('start_date', models.DateField(blank=True, help_text='Start date', null=True)),
                ('sg_start', models.FloatField(blank=True, help_text='Starting specific gravity', null=True, verbose_name='SG Start')),
                ('date', models.DateField(blank=True, help_text='End date', null=True, verbose_name='End Date')),
                ('sg_end', models.FloatField(blank=True, help_text='Ending specific gravity', null=True, verbose_name='SG End')),
                ('abv', models.FloatField(blank=True, help_text='Alcohol by volume (percent)', null=True, verbose_name='ABV (%)')),
                ('lal', models.FloatField(blank=True, help_text='Litres of Absolute Alcohol', null=True, verbose_name='LAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fermentation Record',
                'verbose_name_plural': 'Fermentation Records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TotalsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Totals', help_text='Description', max_length=255)),
                ('faints_to_storage_l', models.DecimalField(blank=True, decimal_places=2, help_text='Faints stored in litres', max_digits=10, null=True, verbose_name='Faints to Storage (L)')),
                ('faints_abv', models.FloatField(blank=True, help_text='ABV of stored faints', null=True, verbose_name='Faints ABV (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Totals Record',
                'verbose_name_plural': 'Totals Records',
            },
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-date'], 'verbose_name': 'Record (Legacy)', 'verbose_name_plural': 'Records (Legacy)'},
        ),
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product identifier (A, B, C, etc.)', max_length=50, verbose_name='Product')),
                ('final_abv', models.FloatField(blank=True, help_text='Final alcohol by volume', null=True, verbose_name='Final ABV (%)')),
                ('final_l', models.DecimalField(blank=True, decimal_places=2, help_text='Final litres', max_digits=10, null=True, verbose_name='Final L')),
                ('distillation_location', models.CharField(blank=True, help_text='Location of distillation', max_length=100, null=True, verbose_name='Distillation Location')),
                ('lal', models.FloatField(blank=True, help_text='Litres of Absolute Alcohol', null=True, verbose_name='LAL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('totals_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='distillery.totalsrecord')),
            ],
            options={
                'verbose_name': 'Product Record',
                'verbose_name_plural': 'Product Records',
                'ordering': ['product_name'],
            },
        ),
    ]
