# Generated by Django 5.1.7 on 2026-01-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0005_rename_harts_out_location_distillationrecord_hearts_out_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalsrecord',
            name='faints_to_storage_location',
            field=models.CharField(blank=True, help_text='Location of faints storage', max_length=100, null=True, verbose_name='Faints to Storage Location'),
        ),
        migrations.AddField(
            model_name='totalsrecord',
            name='hearts_to_storage_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hearts stored in litres', max_digits=10, null=True, verbose_name='Hearts to Storage (L)'),
        ),
    ]
