# Generated by Django 5.1.7 on 2026-01-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0005_distillationrecord_fermentationrecord_totalsrecord_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
