# Generated by Django 5.1.7 on 2026-03-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0006_totalsrecord_faints_to_storage_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washrecord',
            name='sg_end',
        ),
        migrations.RemoveField(
            model_name='washrecord',
            name='sg_start',
        ),
        migrations.AddField(
            model_name='batch',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AddField(
            model_name='distillationrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AddField(
            model_name='fermentationrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AddField(
            model_name='productrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AddField(
            model_name='totalsrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AddField(
            model_name='washrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
    ]
