# Generated by Codex on 2026-06-20

from django.db import migrations, models


def copy_faints_out_location_to_wash(apps, schema_editor):
    Batch = apps.get_model('distillery', 'Batch')

    for batch in Batch.objects.select_related('wash', 'spirit_1', 'spirit_2'):
        if not batch.wash or batch.wash.faints_out_location:
            continue

        location = None
        if batch.spirit_1 and batch.spirit_1.faints_out_location:
            location = batch.spirit_1.faints_out_location
        elif batch.spirit_2 and batch.spirit_2.faints_out_location:
            location = batch.spirit_2.faints_out_location

        if location:
            batch.wash.faints_out_location = location
            batch.wash.save(update_fields=['faints_out_location'])


def copy_faints_out_location_to_spirit(apps, schema_editor):
    Batch = apps.get_model('distillery', 'Batch')

    for batch in Batch.objects.select_related('wash', 'spirit_1'):
        if not batch.wash or not batch.wash.faints_out_location or not batch.spirit_1:
            continue

        batch.spirit_1.faints_out_location = batch.wash.faints_out_location
        batch.spirit_1.save(update_fields=['faints_out_location'])


class Migration(migrations.Migration):

    dependencies = [
        ('distillery', '0008_alter_distillationrecord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='washrecord',
            name='faints_out_location',
            field=models.CharField(blank=True, help_text='Location of faints output', max_length=100, null=True, verbose_name='Faints Out Location'),
        ),
        migrations.RunPython(copy_faints_out_location_to_wash, copy_faints_out_location_to_spirit),
        migrations.RemoveField(
            model_name='distillationrecord',
            name='faints_out_location',
        ),
    ]
