from django.contrib import admin
from django.http import HttpResponse
from .models import Batch, FermentationRecord, WashRecord, DistillationRecord, TotalsRecord, ProductRecord
import csv


def export_batches_to_csv(modeladmin, request, queryset):
    """Admin action to export selected batches and all their records to CSV"""
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="batches_export.csv"'
    
    writer = csv.writer(response)
    
    # Write header
    writer.writerow(['Export Date:', request.META.get('HTTP_HOST', ''), 'Generated by Django Admin'])
    writer.writerow([])
    
    for batch in queryset.order_by('batch_number'):
        # Write batch header info
        writer.writerow(['=' * 80])
        writer.writerow([f'BATCH #{batch.batch_number}'])
        writer.writerow(['=' * 80])
        writer.writerow(['Recipe:', batch.recipe])
        writer.writerow(['Created:', batch.created_at.strftime('%Y-%m-%d %H:%M')])
        writer.writerow(['Updated:', batch.updated_at.strftime('%Y-%m-%d %H:%M')])
        writer.writerow([])
        
        # Export Fermentation
        if batch.fermentation:
            writer.writerow(['--- Fermentation ---'])
            record = batch.fermentation
            writer.writerow(['Field', 'Value'])
            writer.writerow(['To', record.to_field or ''])
            writer.writerow(['Volume (L)', record.volume_in_l or ''])
            writer.writerow(['Start Date', record.start_date.strftime('%Y-%m-%d') if record.start_date else ''])
            writer.writerow(['SG Start', record.sg_start or ''])
            writer.writerow(['End Date', record.date.strftime('%Y-%m-%d') if record.date else ''])
            writer.writerow(['SG End', record.sg_end or ''])
            writer.writerow(['ABV (%)', record.abv or ''])
            writer.writerow(['LAL', record.lal or ''])
            writer.writerow([])
        
        # Export Wash
        if batch.wash:
            writer.writerow(['--- Wash ---'])
            record = batch.wash
            writer.writerow(['Field', 'Value'])
            writer.writerow(['Description', record.description])
            writer.writerow(['Faints In (L)', record.faints_in_l or ''])
            writer.writerow(['From', record.from_field or ''])
            writer.writerow(['To', record.to_field or ''])
            writer.writerow(['Volume (L)', record.volume_in_l or ''])
            writer.writerow(['Start Date', record.start_date.strftime('%Y-%m-%d') if record.start_date else ''])
            writer.writerow(['SG Start', record.sg_start or ''])
            writer.writerow(['End Date', record.date.strftime('%Y-%m-%d') if record.date else ''])
            writer.writerow(['SG End', record.sg_end or ''])
            writer.writerow(['Fores Out (L)', record.fores_out or ''])
            writer.writerow(['Heads Out (L)', record.heads_out or ''])
            writer.writerow(['Harts Out (L)', record.harts_out or ''])
            writer.writerow(['Hearts Out Location', record.harts_out_location or ''])
            writer.writerow(['Tails Out (L)', record.tails_out or ''])
            writer.writerow(['Waste Out (L)', record.waste_out or ''])
            writer.writerow(['ABV (Harts) %', record.abv_harts or ''])
            writer.writerow(['LAL', record.lal or ''])
            writer.writerow([])
        
        # Export Spirit 1
        if batch.spirit_1:
            writer.writerow(['--- Spirit 1 ---'])
            record = batch.spirit_1
            writer.writerow(['Field', 'Value'])
            writer.writerow(['Description', record.description])
            writer.writerow(['Faints In (L)', record.faints_in_l or ''])
            writer.writerow(['From', record.from_field or ''])
            writer.writerow(['To', record.to_field or ''])
            writer.writerow(['Volume (L)', record.volume_in_l or ''])
            writer.writerow(['Start Date', record.start_date.strftime('%Y-%m-%d') if record.start_date else ''])
            writer.writerow(['End Date', record.date.strftime('%Y-%m-%d') if record.date else ''])
            writer.writerow(['Fores Out (L)', record.fores_out or ''])
            writer.writerow(['Heads Out (L)', record.heads_out or ''])
            writer.writerow(['Harts Out (L)', record.harts_out or ''])
            writer.writerow(['ABV (Harts) %', record.abv_harts or ''])
            writer.writerow(['Hearts Out Location', record.harts_out_location or ''])
            writer.writerow(['Tails Out (L)', record.tails_out or ''])
            writer.writerow(['Faints Out Location', record.faints_out_location or ''])
            writer.writerow(['Waste Out (L)', record.waste_out or ''])
            writer.writerow(['LAL', record.lal or ''])
            writer.writerow([])
        
        # Export Spirit 2
        if batch.spirit_2:
            writer.writerow(['--- Spirit 2 ---'])
            record = batch.spirit_2
            writer.writerow(['Field', 'Value'])
            writer.writerow(['Description', record.description])
            writer.writerow(['Faints In (L)', record.faints_in_l or ''])
            writer.writerow(['From', record.from_field or ''])
            writer.writerow(['To', record.to_field or ''])
            writer.writerow(['Volume (L)', record.volume_in_l or ''])
            writer.writerow(['Start Date', record.start_date.strftime('%Y-%m-%d') if record.start_date else ''])
            writer.writerow(['End Date', record.date.strftime('%Y-%m-%d') if record.date else ''])
            writer.writerow(['Fores Out (L)', record.fores_out or ''])
            writer.writerow(['Heads Out (L)', record.heads_out or ''])
            writer.writerow(['Harts Out (L)', record.harts_out or ''])
            writer.writerow(['ABV (Harts) %', record.abv_harts or ''])
            writer.writerow(['Hearts Out Location', record.harts_out_location or ''])
            writer.writerow(['Tails Out (L)', record.tails_out or ''])
            writer.writerow(['Faints Out Location', record.faints_out_location or ''])
            writer.writerow(['Waste Out (L)', record.waste_out or ''])
            writer.writerow(['LAL', record.lal or ''])
            writer.writerow([])
        
        # Export Totals
        if batch.totals:
            writer.writerow(['--- Totals ---'])
            record = batch.totals
            writer.writerow(['Field', 'Value'])
            writer.writerow(['Hearts to Storage Location', record.harts_to_storage_location or ''])
            writer.writerow(['Hearts ABV (%)', record.harts_abv or ''])
            writer.writerow(['Faints to Storage (L)', record.faints_to_storage_l or ''])
            writer.writerow(['Faints ABV (%)', record.faints_abv or ''])
            
            # Add products if any
            products = record.products.all()
            if products.exists():
                writer.writerow([])
                writer.writerow(['Products:'])
                writer.writerow(['Product', 'Final ABV (%)', 'Final L', 'Location', 'LAL'])
                for product in products:
                    writer.writerow([
                        product.product_name,
                        product.final_abv or '',
                        product.final_l or '',
                        product.distillation_location or '',
                        product.lal or ''
                    ])
            writer.writerow([])
        
        writer.writerow([])  # Extra spacing between batches
    
    return response

export_batches_to_csv.short_description = "Export selected batches to CSV"


@admin.register(FermentationRecord)
class FermentationRecordAdmin(admin.ModelAdmin):
    list_display = ('description', 'to_field', 'volume_in_l', 'start_date', 'date', 'abv', 'lal')
    list_filter = ('start_date', 'date')
    search_fields = ('description', 'to_field')
    date_hierarchy = 'date'


@admin.register(WashRecord)
class WashRecordAdmin(admin.ModelAdmin):
    list_display = ('description', 'from_field', 'to_field', 'volume_in_l', 'start_date', 'date', 'abv_harts', 'lal')
    list_filter = ('start_date', 'date')
    search_fields = ('description', 'from_field', 'to_field')
    date_hierarchy = 'date'


@admin.register(DistillationRecord)
class DistillationRecordAdmin(admin.ModelAdmin):
    list_display = ('description', 'from_field', 'to_field', 'volume_in_l', 'start_date', 'date', 'abv_harts', 'lal')
    list_filter = ('start_date', 'date')
    search_fields = ('description', 'from_field', 'to_field')
    date_hierarchy = 'date'


@admin.register(TotalsRecord)
class TotalsRecordAdmin(admin.ModelAdmin):
    list_display = ('description', 'harts_to_storage_location', 'harts_abv', 'faints_to_storage_l', 'faints_abv', 'created_at')
    list_filter = ('created_at',)
    search_fields = ('description',)
    date_hierarchy = 'created_at'


@admin.register(ProductRecord)
class ProductRecordAdmin(admin.ModelAdmin):
    list_display = ('product_name', 'totals_record', 'final_abv', 'final_l', 'distillation_location', 'lal')
    list_filter = ('product_name', 'created_at')
    search_fields = ('product_name', 'distillation_location')
    date_hierarchy = 'created_at'


@admin.register(Batch)
class BatchAdmin(admin.ModelAdmin):
    list_display = ('batch_number', 'recipe', 'created_at', 'updated_at')
    list_filter = ('created_at', 'updated_at')
    search_fields = ('batch_number', 'recipe')
    readonly_fields = ('created_at', 'updated_at')
    date_hierarchy = 'created_at'
    actions = [export_batches_to_csv]

